### ISSUE TITLE
gaspump too big

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#1090]
With the latest git version, these gaspumps are too big. I would say atleast twice as big as they should be.

![Screenshot_Doom_20211225_162304](https://user-images.githubusercontent.com/77861029/147388343-6f101842-d89d-40f5-a6b2-58c953a5bafd.png)

![Screenshot_Doom_20211225_162452](https://user-images.githubusercontent.com/77861029/147388346-e1f2fc2a-33d2-4410-977d-382ce2b1b252.png)

Edit: in this level / version the pump is a normal size:

![Screenshot_Doom_20211120_212438](https://user-images.githubusercontent.com/77861029/147394747-1f75a37d-b646-419b-95a1-f341076ca262.png)

**Comment by Tormentor667** [comment]
Fixed

**Comment by x3003** [comment]
It's not fixed, they're still too big. Even bigger than ascher.

![Screenshot_Doom_20211228_210947](https://user-images.githubusercontent.com/77861029/147603597-92a397ba-dd59-475e-9209-24928b0b5372.png)

![Screenshot_Doom_20211228_211651](https://user-images.githubusercontent.com/77861029/147604081-17bf1592-5aa1-4970-9998-e477bd59e299.png)

And these are even bigger still.

![Screenshot_Doom_20211228_211059](https://user-images.githubusercontent.com/77861029/147603600-4aaa0df2-1a3f-443c-97c3-9944ce7da5d8.png)

![Screenshot_Doom_20211228_211722](https://user-images.githubusercontent.com/77861029/147604040-1aab02fd-edb7-4f83-b3f0-cea38c9c8fe3.png)

**Comment by Tormentor667** [comment]
I fixed the one in the last shot but I think we shouldn't go too deep into any scaling inconsistencies. I mean, I am pretty sure that the care is too large, that tanks are too small and that other comparised objects suffer the same. Even though you are right, the outcome by fixing all these is not worth the effot :) But thanks for mentioning!

**Comment by x3003** [comment]
Could be, but the one in c2m3 has the correct size. Couldn't you copy/paste these settings ?
