### ISSUE TITLE
[3.2] [CaptainJ] Some Nazis on a toilet disappear presumably when going to a pain state.

### ISSUE THREAD

**Issue by Tormentor667** [Realm667/WolfenDoom#1094]
![grafik](https://user-images.githubusercontent.com/10298439/147454060-59ea8293-abb9-4273-a5a7-58154a7ee5e2.png)
![grafik](https://user-images.githubusercontent.com/10298439/147454063-356186d9-fe79-4de4-81a5-19b3b9c2b65c.png)

**Comment by Ozymandias81** [comment]
This happens since ages and sometimes it is "fixed" by moving the actor on top of the wc by 4mp more on normal height of the wc where it sits (map placement), but I guess sometimes they "fall" somehow inside the model and disappear because become unable to find "space" to spawn again. I have never managed to fullfill this issue if not temporarily, then it also changes between GZDoom builds sometimes, but could be a bullshit.

**Comment by AFADoomer** [comment]
I attempted to fix this in 1faa84a2b7041a2d1acc68cd9d87a6ffdf04b615.

But I can't reliably reproduce the problem, so....

**Comment by x3003** [comment]
I got it here, i shot the standing nazi on the toilet. Then he disappeared.

![Screenshot_BoA_20220220_224635](https://user-images.githubusercontent.com/77861029/154866304-be60204e-7c3d-4ec6-afcd-34e8560a0c52.png)

**Comment by AFADoomer** [comment]
Current build?

**Comment by Tormentor667** [comment]
Was it the peeing one?

**Comment by AFADoomer** [comment]
OK, this should be fixed in c11c485e725668ad6cef170e27bf37d40f13de3c.

**Comment by x3003** [comment]
Well, it still doesn't work. When I shoot this one, gone.... Like a magician.

![Screenshot_Doom_20220221_200309](https://user-images.githubusercontent.com/77861029/155013832-1b88ed53-dd18-4a08-bf7e-981ba6c4d80f.png)

**Comment by AFADoomer** [comment]
Wait, is it the dead body that's disappearing?  Or is he disappearing in between pain state and leaving the urinal?

**Comment by x3003** [comment]
It only happens when you shoot him in the back. 1 bullet is enough to make 'the ghost' leak.

![Screenshot_Doom_20220221_201100](https://user-images.githubusercontent.com/77861029/155014547-c4182217-462c-484d-984a-4088514aa64e.png)

![Screenshot_Doom_20220221_201111](https://user-images.githubusercontent.com/77861029/155014559-28cd819a-f22e-46c3-95f7-523be5ca422d.png)

**Comment by AFADoomer** [comment]
Fixed in b607d7e0730e6bd000f58cc64732fd69b6be208f.

**Comment by x3003** [comment]
Seems to work fine now.

**Comment by Username-N00b-is-not-available** [comment]
Cannot reproduce this using any weapon. However the shovel gibs him, as in #1283.
