### ISSUE TITLE
electric chair

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#1129]
With the latest git version, in c1m2, you can sit/stand the electric chair w/o dying. This only happens when you touch the 2 'knobs' on the chair.

![Screenshot_BoA_20220114_170828](https://user-images.githubusercontent.com/77861029/149623057-0139ad0e-c36b-4556-a810-d2dceec80ce8.png)

**Comment by Tormentor667** [comment]
Fixed

**Comment by x3003** [comment]
It wasn't fixed. Tried it w/ the built from yesterday.

![Screenshot_Doom_20220318_173147](https://user-images.githubusercontent.com/77861029/159120931-92f2d11e-6883-4aa7-b379-91e4e72663fe.png)

![Screenshot_Doom_20220318_173216](https://user-images.githubusercontent.com/77861029/159120957-4119c154-234b-49a0-9837-83b29b2284e0.png)

**Comment by Tormentor667** [comment]
No idea what's wrong here, the sectors are all tagged "instant death".

![grafik](https://user-images.githubusercontent.com/10298439/161426517-f7045b5b-a803-4a9a-a62c-26d43509df58.png)
