### ISSUE TITLE
tank drive through bridge

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#1139]
With the latest git version, in c3m2, you can drive the tank through the bridge.

![Screenshot_BoA_20220125_152955](https://user-images.githubusercontent.com/77861029/150996612-d84901a2-3688-46a9-bcf6-fa8a36100c75.png)

**Comment by Tormentor667** [comment]
Are these non-blocking for the player in general?

**Comment by Tormentor667** [comment]
Fixed

**Comment by Talon1024** [comment]
<details><summary>Spoiler</summary>
Can players still get under the bridge? There's a secret area under one of them.
</details>

**Comment by Tormentor667** [comment]
Yes, I made the textures walkable lines so walking below the bridges should still be possible.
