### ISSUE TITLE
effect should sometimes not be triggered

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#1260]
There is a small issue here. You can see the effect when coming from this side, but when you're coming from the other side that effect is lost on the player. So maybe someone can add another line , so that the effect isn't triggered coming from the 'wrong' side and a line which enables it again when you passed the effectline. That way when the player comes back from the right side, the effect is there and they see it.

![Screenshot_BoA_20220610_155039](https://user-images.githubusercontent.com/77861029/173189311-64f6ce8a-8dc4-4d6e-bd64-d19ece92e6bb.png)

**Comment by Tormentor667** [comment]
Fixed, can you confirm?

**Comment by x3003** [comment]
Still doesn't work as expected. The effect is still triggered while you have your back towards the portrait.

**Comment by Tormentor667** [comment]
Well what I did is a change that makes the effect only happen if you come from the side when you walk towards the image. If you turn your back towards it and walk backwards, I can't do anything about it. And at the end, it's just a visual effect and not a game changer :)

**Comment by x3003** [comment]
The effect seems to work now.
