### ISSUE TITLE
part of ceiling too low

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#1286]
In c2m2 this part of the ceiling is too low.

![Screenshot_Doom_20221224_232229](https://user-images.githubusercontent.com/77861029/211144730-f9402a03-27ed-4759-b226-007f3bb921c6.png)

![Screenshot_Doom_20221224_232257](https://user-images.githubusercontent.com/77861029/211144758-dbc36ead-cd44-48e0-8597-5a98159f6342.png)

![Screenshot_Doom_20221225_225722](https://user-images.githubusercontent.com/77861029/211144835-5eec5f5a-1ad4-4610-ae91-e38f5f7618ae.png)

Normally it looks like this, which is the good height:

![Screenshot_Doom_20221224_232420](https://user-images.githubusercontent.com/77861029/211144777-17c77ef8-8bf8-4266-a456-1d0a74e6e130.png)

**Comment by Tormentor667** [comment]
Fixed

**Comment by x3003** [comment]
These ones are still not fixed.

![Screenshot_Doom_20230108_164421](https://user-images.githubusercontent.com/77861029/211205905-574ff094-78dc-4120-99ee-04ae04c41589.png)

![Screenshot_Doom_20230108_164424](https://user-images.githubusercontent.com/77861029/211205915-9a39c23a-0542-43d0-b6d5-0187945c2ba8.png)
