### ISSUE TITLE
Displaying "Mission Objectives" in Multiplayer game results in error

### ISSUE THREAD

**Issue by Tormentor667** [Realm667/WolfenDoom#1380]
![grafik](https://github.com/Realm667/WolfenDoom/assets/10298439/dfd3d2f2-8e4f-469d-99e7-563451ce6c66)

Is it because some kind of an cheat issue? Maybe @AFADoomer or @Talon1024 have an idea.

**Comment by AFADoomer** [comment]
Scripts for multiplayer need to have "net" added to their declaration in order to be run from the console (or keybind) by a player.

See bottom the page here: https://zdoom.org/wiki/Script_types

**Comment by AFADoomer** [comment]
Should be fixed in 6355875e8ade0684877d9d16716406932edd1153, but I didn't run a real multiplayer game to test.

**Comment by Tormentor667** [comment]
Unfortunately not fixed, error still the same:
![grafik](https://github.com/Realm667/WolfenDoom/assets/10298439/ad4748ec-1bdd-450f-9b68-b7edbc25d66a)

It doesn't matter which player tries to display the objectives (host/client), if that makes a difference.

**Comment by AFADoomer** [comment]
Does kicking work?

**Comment by AFADoomer** [comment]
This works fine for me in a locally hosted netgame (though the game desynchs as soon as the map loads...).

**Comment by Tormentor667** [comment]
Currently can't test because of a different error (see "Sharing keys in coop" issue)
