### ISSUE TITLE
repair kit mesage C2M6_B

### ISSUE THREAD

**Issue by hawkwind3** [Realm667/WolfenDoom#1500]
Not the last two messages. You only need one of them.

![repair kit](https://github.com/user-attachments/assets/cfacd23b-d3ef-4a7f-9f46-1f1dda2374e0)

**Comment by Tormentor667** [comment]
A fix has been pushed to master in commit d0cbda0eb (https://github.com/Realm667/WolfenDoom/commit/d0cbda0eb): the generic repair-kit pickup message is suppressed in C2M6_B so that it no longer conflicts with the contextual dialogue. The corresponding LANGUAGE entry has also been marked as unused in the project spreadsheet. Please test this in the current master build and confirm that the resulting behavior matches the intended functionality for this issue.

**Comment by hawkwind3** [comment]
Been thinking on this ..

Correct me if I'm wrong, but I think the player can get the repair kit before finding the broken door mechanism. In that event, the message should read something like "that repair kit might come in handy".

If finding the jammed mechanism after obtaining the repair kit, then I think this should be displayed " Excellent Will, that repair kit you found earlier is exactly what you need to fix the broken door mechanism."

Update - Just checked .... DARRENMESSAGE52 and 53 are still in language.csv without any change. So still not what I was looking for.

**Comment by Tormentor667** [comment]
Can you describe exactly how you would fix it?

**Comment by Tormentor667** [comment]
Follow-up fix pushed to `master` in commit [2929d5bfd](https://github.com/Realm667/WolfenDoom/commit/2929d5bfd5f599e0a57877fdbdfbb3429fa0ddf5).

The C2M6_B repair-kit dialogue now handles both discovery orders without a redundant line:

- Repair kit first: `DARRENMESSAGE58` is shown on pickup, then `DARRENMESSAGE53` when the jammed mechanism is found.
- Jammed mechanism first: `DARRENMESSAGE56` is shown at the mechanism, then `DARRENMESSAGE53` when the repair kit is picked up; returning to the mechanism no longer repeats another line.

`DARRENMESSAGE52` and `DARRENMESSAGE57` are marked as unused in both `language.csv` and the LANGUAGE Google Sheet. The English `DARRENMESSAGE53` text now explicitly says “you found earlier”.

The updated ACS was compiled and C2M6_B loaded successfully in GZDoom 4.14.2 and UZDoom 5.0.0-rc.1. Please test both discovery orders in normal gameplay and confirm that this is the intended final behavior.

**Comment by hawkwind3** [comment]
@Tormentor667 Still not quite right.

An error in script 204 and/or 205.  If you find the jammed mechanism first, and then find the repair kit,
DARRENMESSAGE53 plays, which is incorrect, since you did not get a repair kit earlier.

What you state above should work. Maybe the script needs fixing ?

**Comment by Tormentor667** [comment]
The corrected dialogue branching has now been pushed to `master` in commit [`07436e5ee`](https://github.com/Realm667/WolfenDoom/commit/07436e5ee).

The two possible sequences now produce different, context-correct dialogue:

- Jammed mechanism first, repair kit second: `DARRENMESSAGE56` -> `DARRENMESSAGE52`
- Repair kit first, jammed mechanism second: `DARRENMESSAGE58` -> `DARRENMESSAGE53`

`DARRENMESSAGE52` has also been reactivated in both `language.csv` and the LANGUAGE Google Sheet. I verified both sequences in GZDoom 4.14.2 and UZDoom 5.0.0-rc.1.

Please test this in regular gameplay and confirm that the timing and wording now match the intended functionality.
