### ISSUE TITLE
no enemies coming

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#1587]
In c1m2, when this alarm goes off, no one is coming to check out why the alarm goes off. No enemy is getting spawned. Not even on skill 4....

<img width="1920" height="1080" alt="Image" src="https://github.com/user-attachments/assets/45f41efc-873e-40a8-a64f-a111e387573a" />

**Comment by hawkwind3** [comment]
Fixed. Good catch. Same even in BoA 3.1, so was an old issue.

**Comment by x3003** [comment]
Sorry, this still doesn't work. No-one is coming when activating the panel

**Comment by hawkwind3** [comment]
Finally fixed.
