### ISSUE TITLE
[3.1] Achievements System

### ISSUE THREAD

**Issue by Shockwave508** [Realm667/WolfenDoom#724]
After seeing what the SWWM GZ mod had done with its Achievements system, I've wondered if the BOA team plans on implementing something similar one day?

Examples of possible Achievements would have to do with mission/episode completion, getting 100% kills/secrets/treasure in every playable mission, certain in-game actions (what kind, I don't know), or even tackling the game on Blazkowicz Job/Mein Lieben difficulties.

EDIT by AFADoomer:
List of current achievements (those in bold are planned but not yet implemented; need more supporting work, 🔴 still need icons, 🟡 are incomplete or need re-work, 🟢 are complete):
- Gunslinger! 🟢
Fired 1000 rounds with a pistol.
- Perfectionist 🟢
Finished a level with 100% kills, secrets and treasure!
- Speedrunner 🟢
Finished a level in half its par time!
- Trickster 🟢
Finished a level without collecting all of the keys!
- Impenetrable! 🟢
Finished a level without taking damage!
- Disgrace! 🟢
Finished off a boss with a kick!
- Pacifist 🟢
Finished a level without killing any Nazis!
- Clear Shot 🟢
Sniped an enemy from across the map!
- Watch your step 🟢
Destroyed three enemies with the same placed mine.
- Chevalier 🟢
Defeated a magical skeleton in a fair fight.
- How it was in 1915 🟢
Finished the level with no gas mask!
- Assassin 🟢
Stealthily took out 10 Nazis with the knife!
- Naughty, Naughty... 🟢
It's OK, just a little help...  No one will ever know, right? (Player used 'give' cheat - also resets weapon collection and coint collection achievement counts)
- Stingy 🟢
Finished a level with less than 25 weapon reloads.
- Automatic Weapons 🟢
Let the system do the work.  Finished a level with no manual weapon reloads.
- A Peaceful Solution? 🟢
Allowed more than 5 enemies to surrender!
- Blast-resistant 🟢
Finished a level without using any grenades.
- Demolition Man 🟢
Used 40 grenades!
- Spam, spam, spam, quicksaves, and spam 🟢
Manually saved over 100 times!
- Feel the burn! 🟢
Exhausted your stamina bar 50 times.
- Liquid Death 🟢
Died by drowning in water, burning to death in lava, and dunking yourself in strange purple poison.
- Pesky Problems 🟢
Died to a minor pest...  They are more afraid of you than you are of them, you know?
- Sharpshooter 🟢
Maintained 75% accuracy or higher after firing more than 100 rounds!
- Zombies  🟢
Kill 500 Zombies
- I am Iron Man 🟢
Collected all Eisenmann files.
- Beam me up?  Timey-Wimey? 🟢
Collected all Mayan artifacts.  
- Fully Armed 🟢
Collect all weapons (doesn't include Astrostein or Keen weapons)
- Combat Medic 🟢
Used 20 field kits
- Treasure Hunter 🟢
Opened 20 supply chests
- Gold Digger 🟢
Picked up 1000 coins worth of gold
- Stay Dead 🟢
Killed 50 enemies that were wounded
- Gib 'Em All 🟢
Gib 100 Nazis
- Neat 🟢
Collect all 3 Commander Keen cartridges (Note: This achievement draws with a CK4-style border, background and font)
- Go outside 🟢
Play BoA for more than 10 hours
- Trophy Hunter 🟢 https://github.com/Realm667/WolfenDoom/commit/35711da6c95ba6390d9910c619697ae34bd8f9c6
Collect all three trophy awards (Cacoward, Naziward, Keenaward)
- Dig Deep 🟢
Kill 100 Nazis with the shovel

**Comment by Tormentor667** [comment]
Could be interesting, but a shitload of work

**Comment by AFADoomer** [comment]
I could code it in (just extending the map stats handler, probably), but, yes, it would be a lot of work...  Mostly in developing the list of achievements, the associated thresholds for completion, and (ideally) unique icons for each acheivement.

**Comment by Tormentor667** [comment]
I could help with developing a list of achievements and also with developing unique icons. The coding part would be up to you though. I am sure it would be a lot of fun and replay value for the mod though. So, if you are up to it, count me in (as much support as I can give).

**Comment by DoomJedi** [comment]
Quite some people offered Steam release - mainly for achievements system. So this would answer alot of prayers.

**Comment by Username-N00b-is-not-available** [comment]
I have quite a cold attitude towards achievements in general, but if thought over properly they could add a lot of replay value, maybe even more than the pre-packaged addons.
Personally I think the achievements should be tough challenges (possibly a bit luck-based), mostly map-specific ones, so the process of hunting them does not become boring. I wouldn't consider adding trivial ones at all, they are widely regarded as developer laziness and mocked (Call of Dooty WAD series immediately comes to mind here). Purely statistical things like 'Kill 1945 enemies' or 'Pick 40 medikits up' would also be of little interest to players (sans traditional Doom speedrunning max challenges). I am thinking of some shortcuts/timed challenges/'unintended' ways of progression/etc.
I sadly won't be able to help with implementing/testing them, as I have my exams currently, but would try to come up with some ideas.
***
Some questions on implementation details:
1. The achievements should probably be disabled if addons are loaded — but is there a way to check that via ZScript?
2. Will the achievements be stored in savegames, as opposed to Steam where you gain the achievement on the account once and for all?
3. What is the intended design of the achievement list? I would like to suggest a menu operated by up/down arrow keys, with achievements that have been obtained (and only them) displayed in one or two columns. This will likely mean we will have to strip off the 'Mission Summary' caption from board_hd.png into a separate graphic and add a similar 'Achievements' one.

**Comment by Username-N00b-is-not-available** [comment]
Here are some ideas on the achievements, well, mostly obvious ones, but we need something to start with.
All achievements are obtained during single levels, but are remembered during the whole episode playthrough. Do not give any awards for CK levels (maybe except special CK achievements?).

<details><summary>List</summary>

- Perfectionist: Finished a level with 100% kills, secrets and treasure.
Yes, items are included too. There are not too many of them, and on many maps it is quite easy to get 3x100% (if you know the maps well, of course).

- Speedrunner: Finished a level in half its par time.
For this we would need some par times obviously (Romero-style ones). Or name it 'Timestealer', like in Stronghold?

- Slickster: Finished a level without some of the required keys.
Should not be that difficult for a player, actually, but will require some research on the maps' geometry. Need to compile lists for required keys for each level. Not sure it can be done in every episode (looking at C2).

- Impenetrable: Took no damage during a level.
Overlaps with the instagib addon. Maybe use the Stronghold 'Godlike' name?

- Disgrace: Finished off a boss enemy using kicks.
Could be fun with super soldiers.

- Pacifist: Finished a level without killing any Nazis at all.
Only count human enemies (those who inherit BasicGuard and NaziBoss?). Harming them may or may not be allowed (I prefer the first). Should be possible to complete on lower skills on levels like C1M6 (not too many human enemies), C2M1 (if you take the quick route at the end), C3M0_B, but let us not limit players to these ones :-)

- Clear Shot: Killed an enemy from a very long distance.
Set the minimum distance threshold to 6000, 8000 or even 12000? Needs balancing, it should be a very large distance, the target actor should be barely visible through the Kar98k scope. The player just has to find a good sniping position. Let's use 3D distance here.

- Watch Your Step: Destroyed three enemies with a single deployable mine explosion.
Well, at least it would give this pickup a purpose. No mines in C1.

- Chevalier: Defeated a magical skeleton in a fair fight.
In other words, kill a Loper using only the primary attack of the Firebrand. No other weapons, no grenades, no powerups such as Adrenaline or Totale Macht, no Ascher intervention. The alternative fire should only be allowed for buffing the melee damage, not for ranged attacks.

- How it was in 1915: Survived in a hazardous environment without any special gear.
Finish C3M4 without picking up the gas mask. Inspired by Scuba Steve's feedbacks on the map.
</details>

**Comment by AFADoomer** [comment]
I haven't done much work on the implementation for this at this point, but all of those sound reasonable. My plan was to encode achievement completion in a cvar so that they would be resident across all playthroughs for that player.

**Comment by Username-N00b-is-not-available** [comment]
It would sadly be very easy to counterfeit that CVAR by modifying it in the configuration file or even from the console.

**Comment by AFADoomer** [comment]
Not if I do a basic seeded algorithm to scramble it...  still could be reverse-engineered if someone digs through the scripts, but if they want to go to those lengths, they could fake it regardless.

**Comment by Tormentor667** [comment]
I think adding various "generic" achievements should be added as well, as some kind of "appetizer" - firing a certain amount of bullets, killing a certain amount of enemies, generic stuff of all kind.

**Comment by DoomJedi** [comment]
As alot of stuff are breakable in this mod - I think finishing a level without breaking any scenery is a cool achievement.
Same we can go for "breaking all scenery in a level" - "Elephant in china shop" achievement.

Finishing without use of grenades?
Brutal achievement? How many enemies he killed in brutal death (burn, rpg etc)
Maybe achievement about how many enemies he caused to surrender to him? 
Zombie killer with over 500 kills?
Passing the game without use of any secrets?
Passing BoA without use of sniper scope? ...Or RPG?
We can make achievement for passing the level C3M1 after alerting all enemies at the start of a level? Same for C2M1?
"Stealth is for losers" achievement?

I think we might need "under-achievements" too? Like "anti-medals" of Skulltag?
For many self-kills in a level using your own weapons? "Meaningless death" achievement for many death not from enemy but from environmental dangers, including falling damage, lava etc...? under-achievements for being killed with melee attack or simple pistol?
Killed by critters? Those are always funny as "danger".
Maybe for too many saves and reloads?

**Comment by AFADoomer** [comment]
Most of those are good ideas.  I think they will be pretty easy to implement.

Keep in mind that I need to be able to put a "hook" into the code somewhere to measure something for each achievement; anything with damage to Nazis (or inheriting classes), use of specific weapons, secret counts, reloading, etc. is relatively easy already.  

Stealth checks will probably require some work; I'm not sure how the "Stealth is for losers" one would work; maybe more than 50% of total map ticks spent with enemies alerted?

I already added a "Naughy, naughty..." achievement that is given for using the 'give' cheat, so the anti-medals idea is good, too.  For meaningless deaths: at least one death from lava, poison, and drowning?

Each of these also will need a unique icon.  I was originally considering doing military-style medals for each, but the icons become meaningless then because they are too small...  If I can get help with ~24x24 icon images that fit our style (they can really be ~32x32 to allow for shadows, etc.), that would be very useful.

**Comment by Tormentor667** [comment]
I can take care of the graphics as soon as I know which achievements we will go fot

**Comment by DoomJedi** [comment]
How about average speed (moving speed) achievement?
Average kill rate achievement? Average kills per minute of play or whatever?
How about not picking at all ammo/health dropped my enemies, only standart pickup?
How about for picking ammo/health only from dead enemies, no normal pickups?

**Comment by MuadDib90** [comment]
> 
> 
> I can take care of the graphics as soon as I know which achievements we will go fot

I'd like to (try at least) help in this field too. :)

**Comment by Username-N00b-is-not-available** [comment]
Did not test the system in game, but the code seems solid, and the 'security system' is just the right level (to not be editable by hand, at least). Thank you very much for the implementation, @AFADoomer! If you don't mind, here are some questions:
1. The CVAR is currently defined as user-scope, and is therefore saved into savegames, but not into the config file (I can be wrong here). Does it mean that the player's achievements are reset to zero after restarting GZDoom (but can be loaded from a savegame)? Would this behaviour lead to problems when loading savegames from two different sessions, and could changing `user` to `nosave` help with the situation?
2. Google Books says that 'slikster' without `c` is not used in books: https://books.google.com/ngrams/graph?content=slickster%2Cslikster&year_start=1800&year_end=2019&corpus=26&smoothing=3&direct_url=t1%3B%2Cslickster%3B%2Cc0, is this spelling a reference to something? Also when writing the idea on this achievement I meant that the player should miss _some_, not _all_ of the keys, and still complete the level. I also have severe doubts on the latter being possible to accomplish, but the former definitely _is_ possible.
3. If the 'Watch Your Step' achievement is implemented, I think it would be better to raise the bar to 4 or 5 enemies. 3 could have been good for my proposed system where the achievements are restricted to a savegame.
4. As for the par times, it would be nice to have a playtester (or two) play through the levels as quickly as possible and tell us the time results, but we can also estimate the times based on pagb666's playthrough, for example.
5. Will achievements like 'Sharpshooter' be taken from the player when the corresponding statistics get out of the interval, or they will stay in the list?
***
@DoomJedi Thank you for lots of good suggestions! (I chuckled a bit on reading about the слон в посудной лавке.) I would only like to comment on points from your last message about items: it is impossible to determine by looks of an item if it was dropped from an enemy or set in map editor/spawned via scripts, and there are also lots of cramped spaces and narrow corridors in BoA where you cannot avoid picking items up, so trying to accomplish these achievements could become really frustrating. But for a small single level (e. g. C1M1) the one about avoiding normal pickups can be possible.

**Comment by Tormentor667** [comment]
Some achievement ideas:

- Unlock Operation Eisenmann (collect all Eisenmann Files)
- Unlock Operation Astrostein (collect all Mayan Artifacts)
- Full Arsenal (collect each weapon at least once)
- Chief Physician (use 20 fieldkits)
- Treasure Hunter (open 20 treasure chests)
- Gold Digger (collect 1000 gold)
- Stay Dead (kill 50 soldiers which revived and attacked you sitting)
- Gib'em all! (make 100 soldiers gib/explode)
- It's neat (find all 3 Keen cartridges)
- Wolfenaddicted (play Blade of Agony at least 10 hours)

Just tossing around, pretty sure that you can give better names for them, and no need to add them all, just ideas :)

**Comment by MuadDib90** [comment]
Hi, here are some of my drafts. Size 32x32 as @AFADoomer wanted.
This is just for discussion, and to get an idea, and also as a starting point.

The idea behind it is a frame in which is a some icon, that represent the achievement. The green background means it has something to to with "not to do something" or "be it a peaceful way". Yellow to orange background means it has to do marginally something with killing, but does not necessary means you have to kill to achieve it. And the red one, naturally, has to do something with killing in either way to complete an achievement.

Perfectionist
![Perfectionist](https://user-images.githubusercontent.com/73436978/121063339-78daf680-c7c6-11eb-82a1-0548b5201a41.png)
Gunslinger
![Gunslinger](https://user-images.githubusercontent.com/73436978/121063353-7bd5e700-c7c6-11eb-8023-05c68a9c647f.png)
Clear Shot
![Clear Shot](https://user-images.githubusercontent.com/73436978/121063361-7e384100-c7c6-11eb-9a24-fbc55945f698.png)

**Comment by MuadDib90** [comment]
> 
> 
> Some achievement ideas:
> 
>     * Unlock Operation Eisenmann (collect all Eisenmann Files)
> 
>     * Unlock Operation Astrostein (collect all Mayan Artifacts)
> 
>     * Full Arsenal (collect each weapon at least once)
> 
>     * Chief Physician (use 20 fieldkits)
> 
>     * Treasure Hunter (open 20 treasure chests)
> 
>     * Gold Digger (collect 1000 gold)
> 
>     * Stay Dead (kill 50 soldiers which revived and attacked you sitting)
> 
>     * Gib'em all! (make 100 soldiers gib/explode)
> 
>     * It's neat (find all 3 Keen cartridges)
> 
>     * Wolfenaddicted (play Blade of Agony at least 10 hours)
> 
> 
> Just tossing around, pretty sure that you can give better names for them, and no need to add them all, just ideas :)

As for my opinion, I am really against all achievements, that could be achieved only by reguraly playing the game. That breaks the idea behind it. You have to do something **in addition** to achieve it - that's the point. But that is just my point of view. :)

**Comment by AFADoomer** [comment]
They do serve the purpose of showing the player how achievements work, though.  

I like all of these suggestions, and most are easy enough to implement...  I don't know that we have a good way of tracking total gameplay time right now, though.

**Comment by MuadDib90** [comment]
> 
> 
> They do serve the purpose of showing the player how achievements work, though.

Well, I can understand this, if there are 2 achievements that are there only for that purpose; and are in a good way executed. Otherwise it is what I said. - Again, no hard feelings, only my point of view.

**Comment by Username-N00b-is-not-available** [comment]
Incrementing a counter in WorldTick calls does not seem to be a good solution from the performance perspective :-) , but maybe we can add ```level.maptime``` to the counter on map endings, similarly to MapStatsHandler.

**Comment by AFADoomer** [comment]
Probably the actual WorldUnloaded call.  Need to try to rework how the level exit calls are run anyway, since they only work for crossing lines and 'using' NPCs, not exiting via scripts or console.

**Comment by MuadDib90** [comment]
OK, I'll wait. :)

**Comment by Shockwave508** [comment]
I'd like to throw my hat in the ring for an achievement suggestion: Finishing C1M5 (Operation: Paris) without making use of the Nebelwerfer even once. I admittedly hunkered down during every one of my runs and repeatedly spammed this weapon until Allied reinforcements arrived at Wave 7.

**Comment by Username-N00b-is-not-available** [comment]
@Shockwave508 Would it be a serious achievement for the player? Surely the Nebelwerfer may be way more fun to use than the machine guns, but the turrets spam bullets pretty quickly, so it is hard to get overwhelmed even at the frontmost position if you do not forget to crouch. (I did not even know about that the Nebelwerfer can be shot prior to #800, and had no problems with completing C1M5. I have always considered this battle really easy, especially compared to what we have later on.)
This is not an objection, I would not be against such an achievement, just asking.

**Comment by Tormentor667** [comment]
@AFADoomer just for the record, graphics max size is 32x32 because that's the max amount of pixels for that, right? Or is more possible in case of an higher resolution?

**Comment by AFADoomer** [comment]
Correct. If they need to be bigger,  they can be, but the text will be disproportionately small.

**Comment by Tormentor667** [comment]
Right then I will stick to 32x32 graphics. Will do them this weekend.

**Comment by MuadDib90** [comment]
@AFADoomer @Username-N00b-is-not-available what are the plans for achievement? Some sort of table where you could see which of them are completed? Where will this be accessible? Do we need some accounts system for it? (If I overlooked these information, I apologize for duplicity.)

**Comment by AFADoomer** [comment]
I don't know.  A table would be cool...  I had planned a boring on-screen list.

This will also let me convert the cacoward, Keen award, etc. to achievements and make them spawn only if picked up in play, too.

**Comment by Tormentor667** [comment]
<img width="16" alt="ac_gunslinger" src="https://user-images.githubusercontent.com/10298439/121783184-9684d300-cbad-11eb-8a4d-f7cd73652945.png">
<img width="16" alt="ac_iamironman" src="https://user-images.githubusercontent.com/10298439/121783185-9684d300-cbad-11eb-8a0f-4ad865d3dafd.png">
<img width="16" alt="ac_impenetratable" src="https://user-images.githubusercontent.com/10298439/121783186-971d6980-cbad-11eb-8b46-a6656ad53cb2.png">
<img width="16" alt="ac_liquiddeath" src="https://user-images.githubusercontent.com/10298439/121783187-971d6980-cbad-11eb-8125-db18f4e0f5f2.png">
<img width="16" alt="ac_longplay" src="https://user-images.githubusercontent.com/10298439/121783189-971d6980-cbad-11eb-95ed-0039dc5d5f25.png">
<img width="16" alt="ac_naughtynaughty" src="https://user-images.githubusercontent.com/10298439/121783190-97b60000-cbad-11eb-996a-472a225ba2e2.png">
<img width="16" alt="ac_pacifist" src="https://user-images.githubusercontent.com/10298439/121783191-97b60000-cbad-11eb-889e-c8be14d36079.png">
<img width="16" alt="ac_perfectionist" src="https://user-images.githubusercontent.com/10298439/121783192-97b60000-cbad-11eb-840e-92f97c305a8b.png">
<img width="16" alt="ac_peskyproblems" src="https://user-images.githubusercontent.com/10298439/121783193-984e9680-cbad-11eb-855c-478b87d3524d.png">
<img width="16" alt="ac_sharpshooter" src="https://user-images.githubusercontent.com/10298439/121783194-984e9680-cbad-11eb-9214-711c8ae9f2d8.png">
<img width="16" alt="ac_slikster" src="https://user-images.githubusercontent.com/10298439/121783196-984e9680-cbad-11eb-9e4d-00f85bcfd388.png">
<img width="16" alt="ac_spamspam" src="https://user-images.githubusercontent.com/10298439/121783197-98e72d00-cbad-11eb-98d6-11dc676575d4.png">
<img width="16" alt="ac_speedrunner" src="https://user-images.githubusercontent.com/10298439/121783198-98e72d00-cbad-11eb-9542-d56cda2cc81c.png">
<img width="16" alt="ac_stingy" src="https://user-images.githubusercontent.com/10298439/121783199-98e72d00-cbad-11eb-8b37-58ac546db49a.png">
<img width="16" alt="ac_watchyourstep" src="https://user-images.githubusercontent.com/10298439/121783200-997fc380-cbad-11eb-865c-bfafdf7de647.png">
<img width="16" alt="ac_apeacefulsurrender" src="https://user-images.githubusercontent.com/10298439/121783201-997fc380-cbad-11eb-9724-b3866467dce5.png">
<img width="16" alt="ac_asin1915" src="https://user-images.githubusercontent.com/10298439/121783203-997fc380-cbad-11eb-8b96-a532fbb18df9.png">
<img width="16" alt="ac_assassin" src="https://user-images.githubusercontent.com/10298439/121783204-9a185a00-cbad-11eb-9c87-1dc61f150272.png">
<img width="16" alt="ac_autoweapons" src="https://user-images.githubusercontent.com/10298439/121783205-9a185a00-cbad-11eb-8e2d-f4c148463db9.png">
<img width="16" alt="ac_beammeup" src="https://user-images.githubusercontent.com/10298439/121783207-9a185a00-cbad-11eb-8f77-b5675fad17b9.png">
<img width="16" alt="ac_blastresistant" src="https://user-images.githubusercontent.com/10298439/121783208-9ab0f080-cbad-11eb-96a3-0fdd1f884ccb.png">
<img width="16" alt="ac_chevalier" src="https://user-images.githubusercontent.com/10298439/121783209-9ab0f080-cbad-11eb-9f12-c985fbcf1447.png">
<img width="16" alt="ac_clearshot" src="https://user-images.githubusercontent.com/10298439/121783210-9ab0f080-cbad-11eb-834e-e0ceacc554c1.png">
<img width="16" alt="ac_demolitionist" src="https://user-images.githubusercontent.com/10298439/121783211-9b498700-cbad-11eb-9c71-50bd8491c879.png">
<img width="16" alt="ac_disgrace" src="https://user-images.githubusercontent.com/10298439/121783213-9b498700-cbad-11eb-85f1-e5e95069251d.png">
<img width="16" alt="ac_feeltheburn" src="https://user-images.githubusercontent.com/10298439/121783214-9b498700-cbad-11eb-8180-243a6f3f45a3.png">

**Comment by Tormentor667** [comment]
Finished all, let me know if I missed one, if someone wants to create icons as well, here is the PSD file :)

[achievements.zip](https://github.com/Realm667/WolfenDoom/files/6642559/achievements.zip)

**Comment by MuadDib90** [comment]
> 
> 
> Finished all, let me know if I missed one, if someone wants to create icons as well, here is the PSD file :)
> 
> [achievements.zip](https://github.com/Realm667/WolfenDoom/files/6642559/achievements.zip)

:laughing::laughing::laughing: OK... I can't compete with this it seems, I give up...

**Comment by Tormentor667** [comment]
Can someone tell me which ones are missing?

**Comment by Username-N00b-is-not-available** [comment]
@Tormentor667 The ones missing are mostly the ones which have not even been thought over and implemented yet...
Also there are 34 of them planned currently (@AFADoomer enumerated them starting from zero).

**Comment by Tormentor667** [comment]
I only count 26 in the top post

**Comment by Username-N00b-is-not-available** [comment]
@Tormentor667 See this file: https://github.com/Realm667/WolfenDoom/blob/7b5702b0868b4bc0d019ddbe9e8cc7cbdb456def/scripts/eventhandlers/Tracker.zs#L378

**Comment by Tormentor667** [comment]
The problem here is: Without knowing what the achievements to, I can’t create icons for them

**Comment by AFADoomer** [comment]
Of the ones that are implemented, we're missing an icon for:
- Kill 500 zombies (ACHVMT24.png)
- Collect all (non-Astrostein or Keen) weapons at least once (ACHVMT26.png)

And the icon for Gunslinger needs to be updated to 1000, not 100 (ACHVMT00.png).

**Comment by MuadDib90** [comment]
Guys, shouldn't we use present time instead of past time, when describing achievements?

So for example intead of _\cFSharpshooter\n\cC**Maintained** 75% accuracy or higher after firing more than 100 rounds!_ there would be better to have **Maintain**.

Reason? If achievement is completed, it is OK, but if there will be a table with them, where you could read, what they are about, read it "as completed" sounds odd...
On the other hand, when they are completed, read it as "what had to be done", isn't odd at all.

**Comment by AFADoomer** [comment]
These strings are all shown when the player gets the achievements, so past tense is correct...  But, you are right, we'll need other future tense strings if we want a list of what to do to accomplish the achievements.

A note for anyone trying to debug the achievements:  If you want to clear all achievements, there are four cvars that you have to set to a blank string (""):  
  boa_achievementrecord0
  boa_achievementrecord1
  boa_achievementrecord2
  boa_achievementrecord3

**Comment by MuadDib90** [comment]
Someone has already mentioned somewhere on github (I think), when using "give all" cheat to obtain one particular achievement, when starting the game next time, I get a crash.

Report is enclosed.

[report.txt](https://github.com/Realm667/WolfenDoom/files/6643428/report.txt)

**Comment by Tormentor667** [comment]
Just for the record: I will take care of the missing achievement graphics this ecening

**Comment by MuadDib90** [comment]
Sure 👍 
Also think the problem mentioned above might be in connection with some recent commit. I can't start it at all.
@AFADoomer

**Comment by Tormentor667** [comment]
Just uploaded all missing achievement graphics and fixed the gunslinger

**Comment by Username-N00b-is-not-available** [comment]
@MuadDib90 Can't confirm, I don't get this crash.
@AFADoomer Currently you can get Perfectionist at INTERMAP, not sure if it makes sense.

**Comment by MuadDib90** [comment]
Everything new again. Now it worked.

Tried C1M1 for some achievement hunting with god mode activated, and after finishing level it did not warped me to intermap, but rather kicked me to welcome screen with this line in console:

<code>Attempt to save pointer to unhandled type NativeStruct(Font)</code> (but those brackets were sharp, the code doesn't allow them to display them here)

**Comment by AFADoomer** [comment]
Resolved that problem in 20603beda3ffed9b07f6bc5d0d1dd46c74f69a70.

**Comment by x3003** [comment]
The achievement system looks pretty cool, but will you also see them (for example) on an extended board in the general's room and after finishing a chapter ?

**Comment by AFADoomer** [comment]
> @AFADoomer Currently you can get Perfectionist at INTERMAP, not sure if it makes sense. Also the Blast-resistant achievement does not seem to trigger (I tested it on C1M1), neither does Pesky Problems (C1M2). After trying to trigger these I went to C1M4 and managed to get Clear Shot, so my CVARs were not broken at the time.
> Peaceful Solution does not trigger either, I've already spared 8 scientists and 1 mechanic...

All of these work as expected for me...

**Comment by Username-N00b-is-not-available** [comment]
Also the 'gather 1000 coins' achievement won't workon my machine... Very strange.

**Comment by AFADoomer** [comment]
Using the give cheat resets the count on the coins and weapon types...

**Comment by Username-N00b-is-not-available** [comment]
Yes, it seems that I was using it too often... Spawning 10 TreasureChest2 treasures does help at obtaining it.
Are there any other culprits that could have given problems with Blast-resistant, Pesky Problems, Peaceful Solution?

**Comment by AFADoomer** [comment]
Not that I know of.  

I just tested Blast-resistant by finishing C1M1 without throwing grenades, killed myself my taking a bunch of health and spawning rats to bite me, and spawned/removed scientists until 5 surrendered, and was awarded as expected each time.

Are you sure you didn't already earn these achievements?

**Comment by Username-N00b-is-not-available** [comment]
Well, here are the nonempty achievement records that I have: ```N4M5gzmDOoM7gz2DPYM/gz+DQINBg0ODRINFg0aDRw==``` and ```g0iDSYNKg0uDTINNg06DT4NQg1GDUoNTg1ODVQ==```.

**Comment by AFADoomer** [comment]
Use the current build enter 'neteven printachievements' in the console 😁 .

**Comment by Username-N00b-is-not-available** [comment]
Damn, ```logfile``` does not work properly in this devbuild for some reason, gives
```
Log started: 2021-06-14 00:00:15
]netevent printachievements
]logfile
Log stopped: 2021-06-14 00:00:26
```
Here's my list, and I can say that I definitely did not grab any Mayan artifacts in the achievement builds, nor did I kill 500 zombies, nor finished a level without manual reloads, that's for sure. It appears to me that the encoding/decoding system has a bug somewhere...
![image](https://user-images.githubusercontent.com/59409713/121821822-24db8080-cca4-11eb-9ecd-f236ffe8b229.png)

By the way: 1) I fixed some formatting issues in the CSV (replaced the percent sign which ate the following letter with double percent, changed \c to \n in one instance, removed \n\n\n in zombie achievement), 2) AFAIK we don't have Keenawards or Cacowards on maps except, obviously, INTERMAP (but two or three Naziwards are definitely present).

**Comment by AFADoomer** [comment]
Hmmm...  Have you ever cleared your achievements list?  The parsing changed a couple of times, so you may have some garbage in the system, so to speak.  Liquid Death is impossible to have awarded right now, so something's definitely off.

**Comment by Username-N00b-is-not-available** [comment]
Then yes, there could be leftovers. Last time I deleted it was two days ago, when it still was a single string...
I'll clear it right now and try again testing the achievements tomorrow.

**Comment by AFADoomer** [comment]
> 2) AFAIK we don't have Keenawards or Cacowards on maps except, obviously, INTERMAP (but two or three Naziwards are definitely present).

Crap...  Didn't realize that...  Maybe this should be changed so that there's one per Chapter?  The current Naziwards are in C3M0_A and C2M3.  Would be fitting to do the Cacoward in C1 and the Keen award in C3, given what both were awarded for.  Thoughts?

**Comment by MuadDib90** [comment]
When I try to print achievements @AFADoomer using your command "netevent printachievements", I get a VM abort:


VM execution aborted: string format failed. Expected a pointer for format % p.
Called from AchievementTracker.NetworkProcess at boa.ipk3:scripts/eventhandlers/tracker.zs, line 514
Called from Console.Printf [Native]

**Comment by Username-N00b-is-not-available** [comment]
@MuadDib90 There is a problem with displaying percent signs, could you please change the ones in Czech translation to word 'percent' for now?

**Comment by Username-N00b-is-not-available** [comment]
@AFADoomer Retested from nonexistent CVARs, and I would say that there definitely is a problem. I warped to TEST_LDR, completed some achievements like Chevalier and 4077, then I warped to C1M0, and miraculously a lot of new ones have popped up in the list (shown in green at the bottom part of the attached screenshot):

![achievements](https://user-images.githubusercontent.com/59409713/121870229-7f5bf780-cd0b-11eb-89ef-7f1d293a02b5.png)

**Comment by MuadDib90** [comment]
> 
> 
> @MuadDib90 There is a problem with displaying percent signs, could you please change the ones in Czech translation to word 'percent' for now?

Sure, done. :)

**Comment by MuadDib90** [comment]
@AFADoomer I completed C3M4 without a mask on (also without god mode) and nothing earned.

**Comment by AFADoomer** [comment]
The encoding/decoding has broken at some point for all but the first variable. I'll have to redo it tonight. This causes achievements to not award because they incorrectly show up as already awarded.

**Comment by Username-N00b-is-not-available** [comment]
@MuadDib90
> Sure, done.

Could you please also do the ACHIEVEMENT1 one? The current version does not trigger a VM abort, but I'd remove the percent signs to be sure.

**Comment by MuadDib90** [comment]
> 
> 
> @MuadDib90
> 
> > Sure, done.
> 
> Could you please also do the ACHIEVEMENT1 one? The current version does not trigger a VM abort, but I'd remove the percent signs to be sure.

As you wish. Done.

**Comment by AFADoomer** [comment]
Just updated the tracker in be5ce615c9753e0e85561bb5e6dea4ca41788fb4.  System time for when you completed the achievement is now stored in the CVar.  

Achievements probably all need to be cleared to make sure they show up correctly now...  The number of achievements being stored per CVar was off by one from the proper value, so they may decode incorrectly now (and any that you completed will be dated in 1969 😁)

**Comment by Username-N00b-is-not-available** [comment]
@AFADoomer It was suggested a few times here on GitHub that we show the achievement list in conjunction with the map stats screen, maybe not on the blackboard itself but rather on a sheet of paper (we could use left/right arrows to switch between stats/achievements and up/down to scroll the achievements list).
By the way, if/when we add some new achievements in the future, will the current storage method be backwards compatible?

**Comment by MuadDib90** [comment]
>EDIT: I need ideas for in-game achievement display... and location.

I was thinking about something similar to @Talon1024's message log? Slightly greyish background, and game is paused, so you have time to read all of that. But instead of displaying messages, we can display all achievements in similar manner as "tiles" in windows. Those achieved ones in color, those still unachieved in dark grey (but not much so you can still read it). And it is also srollable, so when new achievement will be added, it'll just display as next one in row or column. Maybe rows with 3 columns each?

So the achievements stats/table will be accessable only from in-game?

---
@Talon1024  also regarding message log, could it be done similary to objectives, as the key bound also exits the message log?

**Comment by Tormentor667** [comment]
I would also recommend some ingame paper in the briefing room near the blackboard

**Comment by MuadDib90** [comment]
And one other thing.
Do we plan some extra explanations of achievements of what you need to do that pop-up after you move your cursor over particular achievement?
Some are pretty obviour, but for example "chevalier" is not...

**Comment by MuadDib90** [comment]
@AFADoomer 
**boa_achievementrecord3** can't be cleared. At least it doesn't work on my device. The others can.
And regarding that achievement board, which is very nice, can we have only 3 columns with scrolling down? For the time being it is hard to read properly.
Also do you plan to add to right down corner of each achievement how much of it is achieved? Similary to that time counter of "get out" achievement.

**Comment by Tormentor667** [comment]
I love the achiement board, I totally love it :) I'd keep the 4 columns though but the small font is indeed at the edge of being readable, I do understand @MuadDib90

**Comment by Username-N00b-is-not-available** [comment]
@MuadDib90 The achievements are stored in the gzdoom-USERNAME.ini file. You can just erase manually the lines which contain these strings.
Some (mostly subjective) comments on current situation:
- I would like to suggest printing a warning at the bottom of or under the achievements board, something like ```Warning: cheats reset your current progress on some of the achievements!```
- Could 'grinding' achievements for which cheating would be next to useless (Gunslinger, quicksave spam and Feel the Burn) be exempt from cheat progress annihilation, please?
- Trophy Hunter needs an icon @Tormentor667;
- We need to establish par times for levels (and show them on the Mission Summary screen?);
- Iron Man/Beam Me Up cannot be finished for now, because Gutenberg is bugged and does not display proper conversations.

**Comment by Tormentor667** [comment]
Par times have already been added by @AFADoomer from YouTube playthroughs

**Comment by AFADoomer** [comment]
@MuadDib90 - You can clear boa_achievementrecord3 manually in the console by entering `set boa_acvievementrecord3 ""` in the console.  It's being used to track achievements that span game/save sessions (play time and a couple of others), so normally shouldn't be reset.

You can clear individual achievements by entering `netevent achievment x -1`, where x is the index of the achievement (so Gunslinger is 0, Treasure Hunter is 28, etc.).  Use 1 instead of -1 to force the achievement to be "accomplished".

**Comment by MuadDib90** [comment]
> 
> 
> I love the achiement board, I totally love it :) I'd keep the 4 columns though but the small font is indeed at the edge of being readable, I do understand @MuadDib90

So can we at least make the description texts like 1,5x or 2x bigger?

**Comment by Tormentor667** [comment]
Just uploaded "Trophy Hunter" achievement graphic, needs proper renaming

**Comment by Username-N00b-is-not-available** [comment]
@AFADoomer
> The only ones that get reset are the total coin count, collecting all weapons, and Keen cartridge collection.

Then I would like to tell you that there is a bug, I've accumulated more than 140 save files (regular saves, not quicksaves) during my recent C2/C3 playthrough, but it was not marked as complete. I do not recall resetting the CVARs during the playthrough.

**Comment by AFADoomer** [comment]
Saves weren't being tracked across gameplay sessions (new game or clean restart not from a save file).  They are now.

**Comment by Username-N00b-is-not-available** [comment]
Implemented two of my suggestions in https://github.com/Realm667/WolfenDoom/commit/a397fbd1b8f43b48b8939e48db6886c9bf8b56b6; @AFADoomer, I think there are still some problems with current progress on the achievements across games and savegames, it does not end up in the configuration file for some reason (the achievement records work fine). Open INTERMAP and make a savegame near the board; pay attention to the current Gunslinger shot amount, say X (it was 0 for me). Type ```map c1m2```, shoot 7 times, load the INTERMAP savegame. It will display X + 7, as expected. Close GZDoom, then load the INTERMAP save again. For me the Gunslinger amount again became zero.

**Comment by MuadDib90** [comment]
I've finished Rastenburg without a gas mask, but did not achieved the 1915 achievement.
What are the conditions again please? Also, could be good to add to the description of that achievement that you have to finish the Rastenburg map to achieve this...

**Comment by Username-N00b-is-not-available** [comment]
@MuadDib90 You should not pick it up on the level at all for the achievement to be accomplished.
I changed the string in the CSV: ```Finished the level with no gas mask!``` -> ```Finished the battle of Rastenburg with no gas mask!```

**Comment by AFADoomer** [comment]
Achievement status not carrying across engine restart and save load should be fixed after a5581978969ca9b76b50477baefd5e99e31c2654.  Hopefully this doesn't break anything else.

**Comment by Username-N00b-is-not-available** [comment]
@AFADoomer This time, when I got to the achievement board on the INTERMAP, it was not shown + I got a VM abort on moving the mouse:
![achVM](https://user-images.githubusercontent.com/59409713/123389983-1c881d00-d5a3-11eb-893e-9074b2e1931c.png)
I fixed this in https://github.com/Realm667/WolfenDoom/commit/cd1cb930381221bce82b7266d2c1c71976221bda by searching for ```AchievementTracker``` in lines akin to
https://github.com/Realm667/WolfenDoom/blob/ad269cfec30a38562b8aec07705f5ec982b71320/scripts/decorate/weapons/granate.zs#L136
and replacing EventHandler with StaticEventHandler. The opposite could also be done, but it is not necessary, since EventHandler is a subclass of StaticEventHandler.
***
After removing the VM abort everything seems to work properly. Thanks!

**Comment by Username-N00b-is-not-available** [comment]
@AFADoomer The problem still does happen (edited my previous post)...
By the way, I also have a suggestion for the menu: would it be possible to show only icons in the list, so the player will be able to click on an icon ('badge'), and a message with the title, icon, description and time would appear (in a message box alike to what is shown now, but it will be shown alone and with a much larger scale than what we have on screen)? @Tormentor667, what do you think about this design?

**Comment by MuadDib90** [comment]
@Username-N00b-is-not-available 
I have proposed a change about it. To show only 3 columns with addition of vertical scroll. That would be sufficient, imo. But @Tormentor667 wanted to keep it. :)

**Comment by Username-N00b-is-not-available** [comment]
What if someone tries to play Blade of Agony on a calculator?
Just kidding :-) IIRC there were some problems with vertical scrolling implementation in BoA (specifically with the help screens), but it might be unrelated. I'm not pushing this suggestion anyway, the important thing for now in this issue is fixing the achievement progress across play sessions. Total play time gets saved, all other achievements do not...

**Comment by MuadDib90** [comment]
Yes, I wanted to report that, but I saw you already did.

**Comment by AFADoomer** [comment]
Save problem should be fixed in aaca3db3153550796757d3bbace37540a1de1216.

**Comment by Username-N00b-is-not-available** [comment]
@AFADoomer This way does not work either... Clear achievements, launch a new game in C1, save near the achievement board, type ```map c1m2```, fire 7 times, reload the save. Gunslinger still shows 0...

**Comment by MuadDib90** [comment]
Shouldn't be the achievements accesable also within the game? (Now they aren't ifaik)

**Comment by AFADoomer** [comment]
@Username-N00b-is-not-available - Of course it does.  You went "back in time" via a savegame.  

Progress like that toward achievements gets reverted to whatever it was at the time of the save. The only progress variables that get saved to the CVar, ignoring savegames, are play time and save count - and the completion of the achievement itself.

**Comment by Shockwave508** [comment]
Thing is, I've fired at least a few hundred pistol rounds, and Gunslinger still registers as 0/1000, even after finishing several missions. I've also abstained from using grenades and manual reloads during C1M1, yet Blast-Resistant and Automatic Weapons didn't unlock. Also did a few backstabs during my most-recent run, yet they didn't contribute to Assassin at all. Here's a screenshot of my progress after C1M3. Most other achievements are progressing as normal, otherwise.

As for Trophy Hunter, all three criteria boxes shouldn't be lit up from the start, unless you grab the appropriate items from certain missions. Got the Cacoward in C1M3, yet the boxes for Chapter 2's Naziward and some "K" trophy, presumably from Chapter 3, are also lit up, despite not being present in my INTERMAP save. Gold Digger doesn't seem to be incrementing normally either, even after several missions; do you specifically have to pick up coins to get this one to unlock, or is it just Gold in general? Also opened three supply chests so far, yet Treasure Hunter registers just one.

![Screenshot_2021-06-26-11-18-18-043_com opentouchgaming deltatouch](https://user-images.githubusercontent.com/32436386/123519373-7f93b580-d670-11eb-821b-588460412e1d.jpg)

**Comment by MuadDib90** [comment]
Awards are uncentered. (Unless there is suppose to be yet something else??)
![01 uncentered awards](https://user-images.githubusercontent.com/73436978/123520181-bd63fe80-d6af-11eb-8b7b-765adfadcf18.PNG)

**Comment by Tormentor667** [comment]
Not supposed to be centered.

**Comment by AFADoomer** [comment]
@Shockwave508 - I just tested all of these with the current build, and they work for me...  Do they behave differently from a fresh game?  

The individual trophy pickups are tracked in the fourth achievements CVar, which isn't cleared automatically (this CVar is also used to track play time and number of saves).  You can clear it manually by entering `set boa_achievementrecord3 ""` in the console, or by entering `netevent achievement 50 -1; netevent achievement 51 -1; netevent achievement 52 -1` to clear the specific trophy records.

**Comment by Shockwave508** [comment]
Just started a fresh run, and it's all working now. Note to self: Always start a fresh playthrough after updating to the newest GitHub build, if any code is edited in the commits.

![Screenshot_2021-06-26-12-58-47-917_com opentouchgaming deltatouch](https://user-images.githubusercontent.com/32436386/123521790-7f021b80-d67e-11eb-9d77-a0faf2251dfa.jpg)

**Comment by Tormentor667** [comment]
Awesome. Thanks for testing it yet another time :)

**Comment by Shockwave508** [comment]
Side note: It seems that Assassin and Gunslinger progress doesn't save between missions/sessions. Gold Digger and Treasure Hunter remain stuck at their current values. Screenshot attached, post-C1M3. Regarding Trophy Hunter, only the Cacoward is sitting on my table at the moment, yet the Keenaward and Naziward icons are still lit up.
![Screenshot_2021-06-26-14-23-17-259_com opentouchgaming deltatouch](https://user-images.githubusercontent.com/32436386/123523709-ed4cdb00-d68a-11eb-9aea-56123d1bf641.jpg)

**Comment by AFADoomer** [comment]
From my previous post:
The individual trophy pickups are tracked in the fourth achievements CVar, which isn't cleared automatically (this CVar is also used to track play time and number of saves). You can clear it manually by entering set boa_achievementrecord3 "" in the console, or by entering netevent achievement 50 -1; netevent achievement 51 -1; netevent achievement 52 -1 to clear the specific trophy records.

**Comment by Shockwave508** [comment]
Followed AFADoomer's instructions to-the-letter, yet all three Trophy Hunter icons still ping as "acquired", despite only having the Cacoward (which should therefore only light up the "C" icon). I suspect it may be an issue with the achievement list itself. As proof, I had set boa_achievementrecord 3 to "" as directed, as the Go Outside achievement shows a playtime of 26 seconds.

![Screenshot_2021-06-26-18-36-33-064_com opentouchgaming deltatouch](https://user-images.githubusercontent.com/32436386/123528540-a7553e80-d6ad-11eb-9052-4f264dc4c112.jpg)

**Comment by AFADoomer** [comment]
Did you start a new game, or restore from a save?

**Comment by Shockwave508** [comment]
Tried both, and the issue persisted. 
Started a fresh game from Chapter 1. Trophy Hunter icons were still lit when I got to the achievement board.
Loaded my most-recent save, before C1M4. Same result.

**Comment by MuadDib90** [comment]
@AFADoomer @Tormentor667 @Username-N00b-is-not-available 
Achievements - I tested nearly all of them.

The picture is the old built - but also tested on the newest one, where the scroll is already available. Nice work btw. Are we planing some discription for at least some of them? Because for example nobody will know they have to fight Loper with only a sword to achieve this one.

- Back to the point. With the function that restores (some) achievements when cheating, I am unable to confirm Keen achievement. I am unable to go through all of it all over again only for this. Sorry guys, can we do something about it? (for testing at least)
- When trying to achieve "year 1915" I encountered this issue: #899
- About that 3 kinds of death. I was able to achieve only drowning in water. Not die in lava nor in purple stuff. (Tried C2M0_A; C2M6_C for lava, and C1M0 for purple water. It did nothing.)
- And finally, I am really concerned about "pacifist" achievement. I don't really think it is possible. I can't imagine any map, where this could be even slightly possible. Only maps, that come to (my) mind, are prison C2M1, docs C2M6_B and Poland C3M0_B. All stealth missions more or less; but in each of them there are choke point(s), where you just have to kill somebody to progress more further. (If I am not mistaken...) -- What dou you think guys?
![01](https://user-images.githubusercontent.com/73436978/123541861-ca7ffc80-d746-11eb-9e87-b8cbf9c65ca5.PNG)

**Comment by Shockwave508** [comment]
Just wanted to confirm that the new Achievement Menu works properly with Delta Touch and gamepads! 👍 

![Screenshot_2021-06-27-08-17-01-811_com opentouchgaming deltatouch](https://user-images.githubusercontent.com/32436386/123546047-add0ce00-d720-11eb-8f52-48604d26bdd0.jpg)

**Comment by Username-N00b-is-not-available** [comment]
@MuadDib90
- Keen achievement: use ```summon Cartridge51``` and the same with 52 or 53 to spawn Commander Keen cartridges near you. See also ```AktenEisenmann``` and ```ArtifactAstrostrein``` (sic, Astros**tre**in), but the achievements for them are awarded when you hand these to Gutenberg.
- C3M4: replied there.
- Three liquid types: it was possible for me, did you try C1M6 for lava? Maybe some textures still do not count towards it. Also, IIRC you do not have to ```drown``` in the purple liquid, but rather die while being damaged by it.
- Pacifist: a very reasonable concern, but I am sure some players will find a way to get it. We are developers, not the top speedrunners, and only they know their skills. Achievements constitute a list of optional tasks, they are not mandatory in any way, and players will be proud if they manage to crack a seemingly impossible one.
By the way, it might be 'much less impossible' on skill 0 :-)

**Comment by Shockwave508** [comment]
Certain incremental achievements still aren't saving between sessions, and/or are stuck, whether they're embedded in savegames or CVARs. Affected achievements are as follows.

1) Gunslinger (resets between sessions)
2) Assassin (resets between sessions)
3) Spam, spam. spam. quicksaves and spam (resets between sessions)
4) Feel The Burn (resets between sessions)
5) Liquid Death (died from drowning in water in C1M2, yet I did not get credit for that?)
6) Treasure Hunter (only registered the supply chest that was opened in INTERMAP/Chapter 1; opened the ones in C1M1 and C1M2, yet did not get credit)
7) Gold Digger (got stuck after picking up all treasure in INTERMAP/Chapter 1 and C1M1; didn't increment after C1M2)
8) Trophy Hunter (only have Cacoward, icons for Keenaward and Naziward are lit up despite not having them)

**Comment by MuadDib90** [comment]
@Username-N00b-is-not-available 
- Summoning Keen cartridges does not work for me. In a way I get all three of them using this console command, but achievement is not completed; although it shows I got all three of them. Strange.
- Also replied there.
- After you mentioned it, I tried. No positive result, unfortunatelly. - And regarding purple water, yes I know that and tried that. No result either. :(
- Well, the thing is, from a tester position I want to point at any incoherencies I can think of. And from my point of view it is undoable; even if I get your point. So I present it here; just to be heard, if for nothing.  :)

**Comment by AFADoomer** [comment]
OK, I re-worked the liquid death means-of-death logic in c10ba7e18634fe45a57ef5ac350bc5e960a757f8, changed some things with how values are read (or not read) from the event handler on save load versus new level in 68059e0230b911ad54b03a7690ddc29b87cb6322, and made some tweaks to the summary screen UI, including fixing the check for trophy pick-ups in f0d49dbd440bfbe689c910cff0d4faf15346af68.

These should fix most of the functionality issues mentioned recently. Should. Please test 😄.

**Comment by MuadDib90** [comment]
Will do, thanks, AFA.

**Comment by Shockwave508** [comment]
Trophy Hunter achievement's working properly now.

May I suggest a tracker on one side of the screen, showing how many of the available achievements you've attained, something like "8/35 Achievements"?

![Screenshot_2021-06-28-05-00-52-116_com opentouchgaming deltatouch](https://user-images.githubusercontent.com/32436386/123654759-01601c00-d7f4-11eb-83d4-774518a653f6.jpg)

**Comment by Shockwave508** [comment]
The Liquid Death achievement still doesn't store its criteria properly; I deliberately drowned myself in C1M2, yet the "blue" box wasn't lit up by the time I returned to INTERMAP.

**Comment by AFADoomer** [comment]
Does it show up immediately after you die and respawn?  Use 'openmenu achievementsummary' in the console to see the board at any time.

**Comment by Shockwave508** [comment]
Had the menu open while drowning in C1M4. The first criteria box turns blue, but it isn't saved to the CVARs, as it returns to its locked-gray state upon loading from your latest save.

**Comment by AFADoomer** [comment]
03d06ac2991bd3d05f2faafaebdbc43a6d7dab44 should resolve this issue.

**Comment by MuadDib90** [comment]
> 
> 
> OK, I re-worked the liquid death means-of-death logic in [c10ba7e](https://github.com/Realm667/WolfenDoom/commit/c10ba7e18634fe45a57ef5ac350bc5e960a757f8), changed some things with how values are read (or not read) from the event handler on save load versus new level in [68059e0](https://github.com/Realm667/WolfenDoom/commit/68059e0230b911ad54b03a7690ddc29b87cb6322), and made some tweaks to the summary screen UI, including fixing the check for trophy pick-ups in [f0d49db](https://github.com/Realm667/WolfenDoom/commit/f0d49dbd440bfbe689c910cff0d4faf15346af68).
> 
> These should fix most of the functionality issues mentioned recently. Should. Please test 😄.

After testing, everything works smootly. Good job, AFA. 👍

**Comment by Shockwave508** [comment]
Liquid Death still isn't registering properly. Drowned myself in C1M2, and it didn't save to the CVARs.

**Comment by AFADoomer** [comment]
From a fresh game?

**Comment by Shockwave508** [comment]
Yep, fresh game, and it didn't save.

**Comment by AFADoomer** [comment]
Where specifically are you drowning yourself?

**Comment by Shockwave508** [comment]
Specifically drowned myself in the drop-down shaft into the shark-infested area, shortly after killing the first Dr. Schabbs Jr..

**Comment by MuadDib90** [comment]
@AFADoomer I tried to drown in C1M2 according to @Shockwave508 and it did counted:
![03 drowning in water set](https://user-images.githubusercontent.com/73436978/123848015-7f691380-d917-11eb-9162-750f5ba09955.PNG)
But the oddity is it caused VM abort:
![02 VM abort](https://user-images.githubusercontent.com/73436978/123848092-99a2f180-d917-11eb-8ef5-e5f4317511ab.PNG)

**Comment by Shockwave508** [comment]
Drowned myself in C1M4, and the blue portion of the Liquid Death achievement was saved properly, and without a VM Abort.

**Comment by AFADoomer** [comment]
I can't reproduce either the failure to log in C1M2 or the VM abort...  I've drowned myself half a dozen times in various places in the tunnel and the value is always saved properly, even across unrelated saves.

I've fixed what I think might have caused the VM abort here: dad605652a01ec5b6090f8bc2a7b40133a446831 - but can't really test.

**Comment by MuadDib90** [comment]
Sure, will test. Thanks.

**Comment by Shockwave508** [comment]
Status of the This Is Neat achievement doesn't save between missions. It pinged correctly with the Red Cartridge after C1M4, yet it returned to a locked grey by the end of C1M5.

**Comment by MuadDib90** [comment]
> 
> 
> Sure, will test. Thanks.
> 
> EDIT: Tested on newest GZDoom dev built and works fine.

**Comment by MuadDib90** [comment]
Btw the current state of achievement board looks really impresive @AFADoomer. Good job. :)

**Comment by x3003** [comment]
Still missing one though. That's when you kill like 100 (or more ?) with the shovel.

**Comment by AFADoomer** [comment]
That's easy enough to add.  Done in 258f3defe5727de929160afbb4c41739c105c629.

**Comment by MuadDib90** [comment]
But in this case, we should except zombies ("Kill 100 enemies (except zombies) with a shovel.").
Because in C3M0_A it is an easy job. All the more the player is using the shovel naturally in here. And there is that side quest of killing 300 zombies...

**Comment by AFADoomer** [comment]
Updated the check to only count Nazi-species actors (except for mutants) in 29ff828e9297b46756553bc31a2bf696ae9d6d2e.
