### ISSUE TITLE
comment boxes

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#820]
After a mission, you can't see comments from douglas and so anymore, because they are pushed out by this new comment boxes very fast.
And if you have multiple of those boxes, these disappear faster than you can read them.

![Screenshot_Doom_20210613_153028](https://user-images.githubusercontent.com/77861029/121809810-9a246280-cc5e-11eb-9db8-847b11fa3bf5.png)

**Comment by AFADoomer** [comment]
This also should be fixed after 20603beda3ffed9b07f6bc5d0d1dd46c74f69a70.

**Comment by x3003** [comment]
No, this isn't fixed yet. The message of Douglas after a mission still only appears very briefly, too short to read.

**Comment by AFADoomer** [comment]
Which mission are you finishing?

**Comment by x3003** [comment]
This time, c1m1 ;)

**Comment by AFADoomer** [comment]
There is no Douglas message in INTERMAP after C1M1...

**Comment by x3003** [comment]
There is a message, but you can only see it very shortly before it disappers (0.5 sec or so). I only guessed it was from douglas, but it could be from someone else.

**Comment by Username-N00b-is-not-available** [comment]
It is the briefing Douglas message from before C1M1.

**Comment by x3003** [comment]
That's still not right then.

**Comment by AFADoomer** [comment]
Try after 211ded6e167e0a335a6c7d5d5716c9f460779caf.

**Comment by x3003** [comment]
It's fixed now. Thx.
