### ISSUE TITLE
[3.2] [Chapter 2] C2 playthrough

### ISSUE THREAD

**Issue by Username-N00b-is-not-available** [Realm667/WolfenDoom#844]
Here are some more playtesting results for Chapter 2 as seen in recent commits. Don't have more time to playtest C3, sorry for that...

- [x] After returning from C2M1 the total treasure count is 47, but the player can get only 46 items from the chest (see also similar problem in C1).

<details><summary>Screenshot</summary>

![Screenshot_BoA_20210616_230107](https://user-images.githubusercontent.com/59409713/122455027-a12bd780-cfb4-11eb-82bf-221cbb93cee6.png)
</details>

> Cannot reproduce.  Did you start a fresh episode, or warp after starting in INTERMAP from another episode/using debug?  - AFA (20 Jun 21)

> Sorry for late reply (I don't read the issue too frequently, and your comment was in a spoiler), but it was after a fresh episode start. It also happened in either C1 or C3 (I don't remember), by the way. <strike>Could it be because of Caco/Nazi/Keenawards?</strike> No, does not seem like it. --N00b, 23 Jun 2021

- [x] You can turn around when reading mission summary, so another 'use' keypress won't deactivate it.

<details><summary>Screenshot</summary>

![Screenshot_BoA_20210617_121150](https://user-images.githubusercontent.com/59409713/122456005-b48b7280-cfb5-11eb-98ba-47850b23d4ed.png)
</details>

- [x] C2M5_B: got 282 of 281 kills.

<details><summary>Screenshot</summary>

![Screenshot_BoA_20210617_134501](https://user-images.githubusercontent.com/59409713/122456563-6460e000-cfb6-11eb-9ffc-5c9503598659.png)
</details>

- [x] If you play with minimal graphical settings (everything off), the AstroDrone death explosion will not spawn if you kill it with the shotgun.
- [x] C2M0_B: tracers (but not the actual bullets) clip through walls sometimes.

<details><summary>Screenshot</summary>

![Screenshot_BoA_20210617_175437](https://user-images.githubusercontent.com/59409713/122456693-85293580-cfb6-11eb-8bc6-dbe106c96822.png)
</details>

> I think the problem here is that the models always clip through walls when they are larger than the wall. Or are the tracers even moving beyond the blocking wall? I think they should at least stop directly where they are. --T667, 2021 June 26th)

> They are sadly moving far beyond the wall, to test warp to (-11332, 5172) on C2M0_B and wake up the guards with a shot... See new screenshot:

<details><summary>Screenshot</summary>

![Screenshot_BoA_20210628_114927](https://user-images.githubusercontent.com/59409713/123607857-eba82200-d806-11eb-8fbf-5414a108caa1.png)

</details>

--N00b, 28 Jun 2021

- [x] Grenade explosion sound does not trigger stealth enemies, they only wake up if damaged by the grenade.

- [x] C2M6_C: the sniper near this position uncrouches and crouches again before each shot.

<details><summary>Screenshot</summary>

![Screenshot_BoA_20210617_194807](https://user-images.githubusercontent.com/59409713/122457025-e2bd8200-cfb6-11eb-969c-bca00d7dde76.png)
</details>

- [ ] HUD problems: words near line beginnings are sometimes drawn in incorrect colours, as shown here (DARRENMESSAGE22, 47, 07 respectively). The translations in the spreadsheet have correct colour codes, I checked.

<details><summary>Screenshot</summary>

![Screenshot_BoA_20210616_211034](https://user-images.githubusercontent.com/59409713/122463323-28317d80-cfbe-11eb-84ac-920b49e455fe.png)
</details>

<details><summary>Screenshot</summary>

![Screenshot_BoA_20210617_193643](https://user-images.githubusercontent.com/59409713/122463363-3089b880-cfbe-11eb-8b9e-0c83d18622f2.png)
</details>

<details><summary>Screenshot</summary>

![Screenshot_BoA_20210617_194323](https://user-images.githubusercontent.com/59409713/122463374-35e70300-cfbe-11eb-9c5e-88ef6997c9db.png)
</details>

***
Resolved issues archive
---
<details><summary>Resolved issues</summary>

- [x] C2M0_B: If you stand at exactly this location, the three moving lasers do not hit you.

> I think this has something to do with the rotation speed of the lasers and I guess we can't do anything about it. There will always be some gaps at certain degrees where "1 tic" is not short enough to cover all radi (is "radi" the plural form of radius?) --T667, 2021 June 26th)

> @Tormentor667 Radii, or just radiuses :-) At first I had thoughts exactly like yours, but then I noticed that the lasers are actually blocked by buttons that switch them off... I would like to repeat my question then: is this supposed behaviour? I would like to change 32x32 buttons to 24x24 here, it should help with the lasers. Revert my commit, please, if the current button height is mandatory. --N00b, 28 Jun 2021

<details><summary>Screenshot</summary>

![Screenshot_BoA_20210617_181958](https://user-images.githubusercontent.com/59409713/122456758-93775180-cfb6-11eb-9105-d5ec793cd5df.png)
</details>

- [x] No Tesla armor offered after Astrostein is completed, the old dialogues are shown both on Rojas and Gutenberg. Related is the problem of no achievements being awarded for handing in 5 Eisenmann files/Mayan artifacts.

> My commit fixed this, I rechecked. --N00b, 23 Jun 2021

- [x] Oops, forgot this one: on C2M4 the planes that are for the player to destroy (eastern part of the map) should be exempt from culling.

> @Talon1024's commit https://github.com/Realm667/WolfenDoom/commit/556617ceff3f37b960cdd12b1652964b448ecefb seems to have fixed it, thanks! --N00b

- [x] C2M1: the invisible MG turrets _in this area_ now activate when the player steps into light even if all guards have been killed (later machinegun towers do not have this problem).

<details><summary>Screenshot</summary>

![Screenshot_BoA_20210616_211437](https://user-images.githubusercontent.com/59409713/122454028-8efd6980-cfb3-11eb-89e8-685ff7739c65.png)
</details>

- [x] C2M2: the doll easter egg does not fall from the tubes anymore, there are no lines that would trigger the script...

<details><summary>Screenshot</summary>

![Screenshot_BoA_20210616_225442](https://user-images.githubusercontent.com/59409713/122454989-95401580-cfb4-11eb-8ff8-976f1a8bc988.png)
</details>

- [x] @AFADoomer, is it possible to log radio messages into console, too, so the player could re-read them if they missed something?

> Not until/unless the pull request that I put in on GZDoom a couple of weeks ago gets accepted or redone by someone else...  That's why the MessageLogMenu menu was added, I think. - AFA (20 Jun 21)

> Done by @AFADoomer in https://github.com/Realm667/WolfenDoom/commit/d88ed277c3930434f533c1be703c71688b4245c4 --N00b

- [x] C2M5_B: there is a tiny sector that the player can bump his head into when going up, could the multiple texture effect be achieved with a 3D floor instead?

<details><summary>Screenshot</summary>

![Screenshot_BoA_20210617_133728](https://user-images.githubusercontent.com/59409713/122456380-282d7f80-cfb6-11eb-97b4-7e12ef0d3f78.png)
</details>

- [x] By the way, the pickup message for the shards says +1 Armor instead of +5 (as it was with Stahlhelm).

- [x] C2M6_B: dead guard companies all across the map keep talking.

> Fixed by @Tormentor667? --N00b || Yes --T667

- [x] C2M6_C: Mikkel's talking head in the dialogue does not talk.

<details><summary>Screenshot</summary>

![Screenshot_BoA_20210617_195410](https://user-images.githubusercontent.com/59409713/122457108-f963d900-cfb6-11eb-9568-51076397e041.png)
</details>

> I don't understand, why this isn't working. The setup in the map dialogue scripts is correct and the graphics are there as well. --T667, 2021 June 26th)

- [x] C2M3: this doorway blocks bullets and enemy sight.

<details><summary>Screenshot</summary>

![Screenshot_BoA_20210617_110658](https://user-images.githubusercontent.com/59409713/122455058-aa1ca900-cfb4-11eb-8a6d-73edc4dd9ec6.png)
</details>

<details><summary>Screenshot</summary>

![Screenshot_BoA_20210617_110729](https://user-images.githubusercontent.com/59409713/122455135-bdc80f80-cfb4-11eb-9983-8713af2e30d5.png)
</details>

- [x] C2M0_A: the Adrenaline secret sector is too thin so the secret does not reliably register, maybe some detail from the pillar could be removed and the larger sector be made secret instead?

<details><summary>Screenshot</summary>

![Screenshot_BoA_20210617_173847](https://user-images.githubusercontent.com/59409713/122456588-69be2a80-cfb6-11eb-9cb5-ef292d7822bd.png)
</details>

- [x] C2M6_B: these two enemies count towards kills, preventing 100% kills on the level.

<details><summary>Screenshot</summary>

![Screenshot_BoA_20210617_193539](https://user-images.githubusercontent.com/59409713/122457014-de916480-cfb6-11eb-93ae-418ceace4149.png)
</details>

- [x] C2M6_C: two dogs outside the play area (see the lower part of the screenshot). You can get them with grenades, but a non-cheating player would not even know that they are here.

<details><summary>Screenshot</summary>

![Screenshot_BoA_20210617_201258](https://user-images.githubusercontent.com/59409713/122457209-17313e00-cfb7-11eb-8a4e-47168e108708.png)
</details>

- [x] C2M1: non-solid window:

<details><summary>Screenshot</summary>

![Screenshot_BoA_20210616_210709](https://user-images.githubusercontent.com/59409713/122453996-83aa3e00-cfb3-11eb-82dd-d05c61ca609a.png)
</details>

- [x] C2M1: this railing and ones nearby have textures but do not block player.

<details><summary>Screenshot</summary>

![Screenshot_BoA_20210616_214827](https://user-images.githubusercontent.com/59409713/122454087-a50b2a00-cfb3-11eb-86f6-a9931b8f5189.png)
</details>

- [x] No turn over hint is shown anymore when reading text papers. Intended?

<details><summary>Screenshot</summary>

![Screenshot_BoA_20210616_223602](https://user-images.githubusercontent.com/59409713/122454114-ad636500-cfb3-11eb-9dc2-c5194870ffa6.png)
</details>

> Fixed in 2be40a528183b6ade4207cf879f551faafdf856c.  - AFA (18 Jun 2021)
- [x] C2M2: IIRC this officer was stuck in the crate.

<details><summary>Screenshot</summary>

![Screenshot_BoA_20210616_224141](https://user-images.githubusercontent.com/59409713/122454157-be13db00-cfb3-11eb-861d-3b8241a6b4ea.png)
</details>

- [x] C2M3: is it intended that the most obvious straight path here does not contain any mines?

<details><summary>Screenshot</summary>

![Screenshot_BoA_20210617_111042](https://user-images.githubusercontent.com/59409713/122455193-ce788580-cfb4-11eb-873f-94de7739da56.png)
</details>

- [x] C2M3: Graf Holzbein actor needs to be made higher, his head clips into ceiling:

<details><summary>Screenshot</summary>

![Screenshot_BoA_20210617_112716](https://user-images.githubusercontent.com/59409713/122455818-7db55c80-cfb5-11eb-98cb-f9cf732ec9af.png)
</details>

- [x] C2M3: problems with door offsets:

<details><summary>Screenshot</summary>

![Screenshot_BoA_20210617_120409](https://user-images.githubusercontent.com/59409713/122455870-8d34a580-cfb5-11eb-9475-d3c97e10d872.png)
</details>

- [x] C2M5_B: typewriter stuck in ceiling:

<details><summary>Screenshot</summary>

![Screenshot_BoA_20210617_132650](https://user-images.githubusercontent.com/59409713/122456187-edc3e280-cfb5-11eb-9252-c7af3c24e9e6.png)
</details>

- [x] C2M5_B: lock on improper side of door, 3x:

<details><summary>Screenshot</summary>

![Screenshot_BoA_20210617_133205](https://user-images.githubusercontent.com/59409713/122456217-fae0d180-cfb5-11eb-8abb-1714d603ad5b.png)
</details>

<details><summary>Screenshot</summary>

![Screenshot_BoA_20210617_133354](https://user-images.githubusercontent.com/59409713/122456273-0a601a80-cfb6-11eb-8c7a-f4a40d05d32c.png)
</details>

<details><summary>Screenshot</summary>

![Screenshot_BoA_20210617_133412](https://user-images.githubusercontent.com/59409713/122456317-177d0980-cfb6-11eb-86f5-fa64026d7543.png)
</details>

- [x] C2M5_B: Improper swastika direction on model (intended?)

<details><summary>Screenshot</summary>

![Screenshot_BoA_20210617_133911](https://user-images.githubusercontent.com/59409713/122456428-3a0f2280-cfb6-11eb-8918-1fa1d646fb9e.png)
</details>

- [x] I think this sprite (this is what we have for armor shards currently) does not fit the map, it resembles the Doom stimpack too much and is really 'abstract' (impossible to guess what it is until you pick it up). The old version suited the map better, I think. Note that the status bar still has a small icon of the old version.

<details><summary>Screenshot</summary>

![Screenshot_BoA_20210617_175500](https://user-images.githubusercontent.com/59409713/122456741-8f4b3400-cfb6-11eb-95f2-b34da797450d.png)
</details>

- [x] Same comment as with the shard applies here as well.

<details><summary>Screenshot</summary>

![Screenshot_BoA_20210617_182103](https://user-images.githubusercontent.com/59409713/122456806-a1c56d80-cfb6-11eb-9506-a7c5f8acbcbb.png)
</details>

- [x] C2M6_B: in the storage area, some of the guards on 3D floors are stuck in railings.

<details><summary>Screenshot</summary>

![Screenshot_BoA_20210617_190353](https://user-images.githubusercontent.com/59409713/122456884-b99cf180-cfb6-11eb-8834-5ddf1b0a6f92.png)
</details>

- [x] C2M6_B: some of the pillars with life-buoy textures are aligned incorrectly.

<details><summary>Screenshot</summary>

![Screenshot_BoA_20210617_190839](https://user-images.githubusercontent.com/59409713/122456904-bf92d280-cfb6-11eb-9014-e7766511261f.png)
</details>

- [x] C2M6_B: crate submerged into asphalt.

<details><summary>Screenshot</summary>

![Screenshot_BoA_20210617_191048](https://user-images.githubusercontent.com/59409713/122456940-c7527700-cfb6-11eb-8462-1ac1ae97afbc.png)
</details>

- [x] C2M6_B: door texture alignment.

<details><summary>Screenshot</summary>

![Screenshot_BoA_20210617_191200](https://user-images.githubusercontent.com/59409713/122456954-ccafc180-cfb6-11eb-8757-a0374e8c496c.png)
</details>

- [x] C2M6_B: the officer who checks documents keeps hitting invisible walls. If I throw a grenade under him, the walls do not help him stay in his place, and he flies away onto the submarine deck...

<details><summary>Screenshot</summary>

![Screenshot_BoA_20210617_192625](https://user-images.githubusercontent.com/59409713/122456973-d1747580-cfb6-11eb-84ce-4842c3782c84.png)
</details>

- [x] C2M6_B: very old bug, this alarm panel slides upwards when destroyed.

<details><summary>Screenshot</summary>

![Screenshot_BoA_20210617_192919](https://user-images.githubusercontent.com/59409713/122456994-d6d1c000-cfb6-11eb-9487-8bb050b79a95.png)
</details>

- [x] C2M6_C: the secret hint mark appears on wrong floor (it is one floor higher).

<details><summary>Screenshot</summary>

![Screenshot_BoA_20210617_195009](https://user-images.githubusercontent.com/59409713/122457045-e81acc80-cfb6-11eb-913e-6eb04ef9168f.png)
</details>

- [x] C2M6_C: Mikkel could be killed using explosives and the flamethrower.

<details><summary>Screenshot</summary>

![Screenshot_BoA_20210617_195234](https://user-images.githubusercontent.com/59409713/122457077-f0730780-cfb6-11eb-90b0-3422d42a46f0.png)
</details>

- [x] C2M6_C: this turret faces wrong direction.

<details><summary>Screenshot</summary>

![Screenshot_BoA_20210617_195813](https://user-images.githubusercontent.com/59409713/122457129-008ae700-cfb7-11eb-8f9a-ef1a06457517.png)
</details>

- [x] C2M6_C: this railing blocks bullets, both from enemies and players.

<details><summary>Screenshot</summary>

![Screenshot_BoA_20210617_195947](https://user-images.githubusercontent.com/59409713/122457158-0680c800-cfb7-11eb-8f76-f91f9e071455.png)
</details>

- [x] Commander Keen death screen has bugged appearance + both options restart the level, so you cannot exit to INTERMAP.

<details><summary>Screenshot</summary>

![ck2](https://user-images.githubusercontent.com/59409713/122464749-e43f7800-cfbf-11eb-960c-3bfb3c2e8055.png)
</details>

> Functional problem should be fixed in e3592f6c6ebe4fa38336f8d1745c191255e96320.  Still working on fixing the selector box drawing. - AFA (18 Jun 2021)

- [x] These typewriters have too high hitboxes, it was a problem when fighting SS in this room: _[assigned to @Ozymandias81]_

<details><summary>Screenshot</summary>

![Screenshot_BoA_20210617_125900](https://user-images.githubusercontent.com/59409713/122456121-db49a900-cfb5-11eb-8256-13d00a781588.png)
</details>

- [x] C2M5_B: the Schleussen parts that the flying saucer crashes into should not be culled. _[assigned to @AFADoomer]_

<details><summary>Screenshot</summary>

![Screenshot_BoA_20210617_134047](https://user-images.githubusercontent.com/59409713/122456488-4f844c80-cfb6-11eb-9e12-37640d086f03.png)
</details>

- [x] On the INTERMAP you can use field kits and bandages, this should not be allowed.

</details>

Stats screen (used noclip cheat to kill two soldiers in C2M6_B):

<details><summary>Screenshot</summary>

![Screenshot_BoA_20210617_201619](https://user-images.githubusercontent.com/59409713/122457247-1e584c00-cfb7-11eb-9ff0-cb8cad8ed648.png)
</details>

**Comment by x3003** [comment]
>C2M1: the invisible MG turrets in this area now activate when the player steps into light even if all guards have been killed (later machinegun towers do not have this problem).

You can kill the guards in these 3 towers, but not the ones who projects the lights. **They** see you when you get in the light. So that looks normal behaviour.

>You can turn around when reading mission summary, so another 'use' keypress won't deactivate it.

That's because you turned away from the board. If you face the board again, you can use the use key again.

**Comment by Username-N00b-is-not-available** [comment]
>**They** see you when you get in the light

There are no guards in upper parts of the corner towers, only automatic turrets. Well, maybe this is not an issue after all, since just after this map we have C2M2 with self-controlling drones, and this MGTurret system could also be thought to be controlled automatically (contrarily to wooden towers later on the way).

> That's because you turned away from the board. If you face the board again, you can use the use key again.

Yes, I know, I have written just that in the issue. My point is, the player should not be able to turn at all when reading the board (thinking of ```SetPlayerProperty(1, 1, PROP_TOTALLYFROZEN)``` — but would it allow ZScript menu keypresses?)

**Comment by AFADoomer** [comment]
Just move...  The board will close.

**Comment by AFADoomer** [comment]
Keen issues should be resolved after 2d90450ac7506db39497a591122abf39a0168fac.  Please verify.

**Comment by Username-N00b-is-not-available** [comment]
> Keen issues should be resolved after 2d90450
@AFADoomer Yes, it works fine now, thanks!

**Comment by Username-N00b-is-not-available** [comment]
@Tormentor667 In C2M0_B, are the lasers supposed to be blocked by the switch buttons? Should the buttons be made smaller?
![Screenshot_BoA_20210623_231804](https://user-images.githubusercontent.com/59409713/123162452-49d8ac00-d479-11eb-9ea8-d82a37a55995.png)

This is the last urgent problem in this issue.

**Comment by Tormentor667** [comment]
Commnted a few things.

**Comment by Ozymandias81** [comment]
Regarding the issue with animated mugshots, all those actors which have more than 5 frames (0-4) keeps showing the 5th frame only and stop @AFADoomer @Username-N00b-is-not-available @Talon1024

**Comment by Tormentor667** [comment]
Fixed one issue.

I also wonder if this problem...

> HUD problems: words near line beginnings are sometimes drawn in incorrect colours, as shown here (DARRENMESSAGE22, 47, 07 respectively). The translations in the spreadsheet have correct colour codes, I checked.

...has been fixed in the meantime @Username-N00b-is-not-available as a lot of improvements have been made to the system.

**Comment by Tormentor667** [comment]
Just took a look at the remaining issues, nothing I can take care of. What about our coders @Talon1024 @AFADoomer @Username-N00b-is-not-available @Ozymandias81 ?

**Comment by Username-N00b-is-not-available** [comment]
Two remaining issues are not fixed yet as of 19 Apr 2023 (checked them now).
